//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticalFunction.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal partial class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PracticalFunction.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Body decays time in seconds. 的本地化字符串。
        /// </summary>
        internal static string Config_BodyDecaysTime {
            get {
                return ResourceManager.GetString("Config_BodyDecaysTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slave Corpse Disposal Cost. 的本地化字符串。
        /// </summary>
        internal static string Config_CostOfDisposingCorpse {
            get {
                return ResourceManager.GetString("Config_CostOfDisposingCorpse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Infertile Monster Disposal Cost. 的本地化字符串。
        /// </summary>
        internal static string Config_CostOfDisposingInfertileMonster {
            get {
                return ResourceManager.GetString("Config_CostOfDisposingInfertileMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prevent Slave Escape from Brothel. 的本地化字符串。
        /// </summary>
        internal static string Config_DisableSlaveEscape {
            get {
                return ResourceManager.GetString("Config_DisableSlaveEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flora&apos;s Overwork Dismantle Limit (-1 = Immune to overwork). 的本地化字符串。
        /// </summary>
        internal static string Config_DismantlingLimit {
            get {
                return ResourceManager.GetString("Config_DismantlingLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow Dragging Units during Pause. 的本地化字符串。
        /// </summary>
        internal static string Config_DragDuringPause {
            get {
                return ResourceManager.GetString("Config_DragDuringPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tentacle Eggs Required to Build Tentacle Room. 的本地化字符串。
        /// </summary>
        internal static string Config_EggForTentacleRoom {
            get {
                return ResourceManager.GetString("Config_EggForTentacleRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Essence Cost to Build Tentacle Room. 的本地化字符串。
        /// </summary>
        internal static string Config_EssenceForTentacleRoom {
            get {
                return ResourceManager.GetString("Config_EssenceForTentacleRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tentacle Egg Essence Conversion Value. 的本地化字符串。
        /// </summary>
        internal static string Config_EssenceOfTentacleEgg {
            get {
                return ResourceManager.GetString("Config_EssenceOfTentacleEgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game day length in seconds. 的本地化字符串。
        /// </summary>
        internal static string Config_Gamedaylength {
            get {
                return ResourceManager.GetString("Config_Gamedaylength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More Game Speed multipliers. 的本地化字符串。
        /// </summary>
        internal static string Config_GameSpeedExtensions {
            get {
                return ResourceManager.GetString("Config_GameSpeedExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loan Period (Days) . 的本地化字符串。
        /// </summary>
        internal static string Config_LoanPeriod {
            get {
                return ResourceManager.GetString("Config_LoanPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum Essence Storage. 的本地化字符串。
        /// </summary>
        internal static string Config_MaxEssence {
            get {
                return ResourceManager.GetString("Config_MaxEssence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sell Character on Delete Key Press. 的本地化字符串。
        /// </summary>
        internal static string Config_OneClickSell {
            get {
                return ResourceManager.GetString("Config_OneClickSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The percentage of Health at which a Slave becomes Drained. 的本地化字符串。
        /// </summary>
        internal static string Config_PercentThatChangesToDrain {
            get {
                return ResourceManager.GetString("Config_PercentThatChangesToDrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pixy move duration multiplier. 的本地化字符串。
        /// </summary>
        internal static string Config_PixyMoveDurationMultiplier {
            get {
                return ResourceManager.GetString("Config_PixyMoveDurationMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tentacle Egg Selling Price. 的本地化字符串。
        /// </summary>
        internal static string Config_PriceOfTentacleEgg {
            get {
                return ResourceManager.GetString("Config_PriceOfTentacleEgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Personal Estate Price.(Does not affect tooltips) 的本地化字符串。
        /// </summary>
        internal static string Config_PrivateEstateCost {
            get {
                return ResourceManager.GetString("Config_PrivateEstateCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The time in seconds that a Slave will rest before starting a new activity. 的本地化字符串。
        /// </summary>
        internal static string Config_RestTime {
            get {
                return ResourceManager.GetString("Config_RestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initial Funds at Game Start. 的本地化字符串。
        /// </summary>
        internal static string Config_StartGold {
            get {
                return ResourceManager.GetString("Config_StartGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time to Death/Fertility after STD Infection in seconds. 的本地化字符串。
        /// </summary>
        internal static string Config_TimeToDieFromVenerealDisease {
            get {
                return ResourceManager.GetString("Config_TimeToDieFromVenerealDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot sell during birth. 的本地化字符串。
        /// </summary>
        internal static string Message_NoSellBirth {
            get {
                return ResourceManager.GetString("Message_NoSellBirth", resourceCulture);
            }
        }
    }
}
